version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'journal-db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: 'gnomis/journal:latest'
    container_name: 'journal'
    environment:
      - 'spring.sql.init.mode=always'  
    ports:
      - "1234:1234"
    depends_on:
      - postgres
  report:
    image: 'gnomis/report:latest'
    container_name: 'report'
    environment:
      - 'api.url=http://journal:1234/api/'
    ports:
      - "8088:8088"
    depends_on:
      - app
volumes:
  db:


